services:
  app:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    init: true
    working_dir: /var/www/html
    ports:
      - "${PORT:-8888}:80"