services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    init: true
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "8888:80"
      - "5173:5173"
    command: apache2-foreground