version: '3'

services:
  app:
    build: .
    ports:
      - 7779:80
    volumes:
      - .:/var/www/html
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
